FROM node:20.9.0-alpine3.18
WORKDIR /backend
COPY . .
RUN mkdir -p logs
RUN mkdir -p upload
RUN npm install

CMD ["npm","start"]
EXPOSE 8000

# --------------------------------
# $ cd /backend
# $ docker build -t backend .
# $ docker run -p 8000:8000 --name backend backend
# $ docker run -d -p 8000:8000 --name backend backend # daemon
# Browser: http://localhost:8000